In [1]:
import torch
print(torch.__version__)

2.12.1


In [2]:
#创建一个张量的排列
import torch 
x = torch.arange(12)
print(x)
print(x.shape)
print(type(x))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
<class 'torch.Tensor'>


In [5]:
#重新定义张量的形状
y = x.reshape(3,4)
print(y)
print(y.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [6]:
#广播机制
a= torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
print(a)
print(b)
print(a+b)


tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [8]:
import torch 
x = torch.arange(12).reshape(3,4)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [13]:
print(x[0]) #取第0行
print(x[1]) #取第一行
print(x[2]) #取第二行
print(x[-1]) #取最后一行，这个的意思是从后往前数的di yi

tensor([0, 1, 2, 3])
tensor([4, 5, 6, 7])
tensor([ 8,  9, 10, 11])
tensor([ 8,  9, 10, 11])


In [24]:
#索引和张量
print(x[1,2])   #打印第一行 第二个数字
print(x[2,3])   #打印第二行 第一个数字，记住张量有第0行 python所有的索引都是从0开始  
print(x[0,2])
print(x[:,1])   #取所有行的第一列
print(x[1:3,2:4])#取1-2行，第2-3列
print(x[2,1])
print(x[:,2])
print(x[0:2,1:3])  #这里有个左闭右开的原则 ，左边包含右边不包含就是我写2 就是取1 ，我写4就是取3
print(x[1:2,5:6])

tensor(6)
tensor(11)
tensor(2)
tensor([1, 5, 9])
tensor([[ 6,  7],
        [10, 11]])
tensor(9)
tensor([ 2,  6, 10])
tensor([[1, 2],
        [5, 6]])
tensor([], size=(1, 0), dtype=torch.int64)


In [3]:
import os 
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..','data','welding.csv')

with open(data_file, 'w') as f:
    f.write('电流,电压,压力,焊接质量\n')
    f.write('150,220,3.5,良好\n')
    f.write('160,NA,3.8,良好\n')
    f.write('145,215,NA,不良\n')
    f.write('145,215,NA,不良\n')


In [4]:
import os  
#用os库创建csv文件，存储焊接参数
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'welding.csv')

with open(data_file, 'w') as f:
    f.write('电流,电压,压力,焊接质量\n')
    f.write('150,220,3.5,良好\n')
    f.write('160,NA,3.8,良好\n')
    f.write('145,215,NA,不良\n')
    f.write('170,230,4.0,良好\n')

In [5]:
import pandas as pd 
#用pandas 读取csv发现缺失值NaN
data = pd.read_csv(data_file)
print(data)

    电流     电压   压力 焊接质量
0  150  220.0  3.5   良好
1  160    NaN  3.8   良好
2  145  215.0  NaN   不良
3  170  230.0  4.0   良好


In [7]:
#用每列的平方值填充缺失值
inputs = data.iloc[:,0:3]  #取前3列（电流，电压，压力）
inputs = inputs.fillna(inputs.mean())
print(inputs)

    电流          电压        压力
0  150  220.000000  3.500000
1  160  221.666667  3.800000
2  145  215.000000  3.766667
3  170  230.000000  4.000000


In [8]:
import torch  用平均值NaN再转成张量给模型用
x=torch.tensor(inputs.values)
print(x)

tensor([[150.0000, 220.0000,   3.5000],
        [160.0000, 221.6667,   3.8000],
        [145.0000, 215.0000,   3.7667],
        [170.0000, 230.0000,   4.0000]], dtype=torch.float64)


In [3]:
import torch
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a)
print(b)


tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


In [7]:
print (a + b)

tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [10]:
#模拟3条焊接记录，每行是【电流，电压，压力】
data = torch.tensor([[150.0,220.0,3.5],
                    [160.0,225.0,3.8],
                    [145.0,215.0,3.6]])

#权重：电流权重0.6 电压权重0.3 压力权重0.1 
weight = torch.tensor([0.6,0.3,0.1])

print(data.shape)
print(weight.shape)

torch.Size([3, 3])
torch.Size([3])


In [11]:
result = data * weight 
print(result)

tensor([[90.0000, 66.0000,  0.3500],
        [96.0000, 67.5000,  0.3800],
        [87.0000, 64.5000,  0.3600]])


In [13]:
score = (data * weight).sum(dim = 1)
print(score)

tensor([156.3500, 163.8800, 151.8600])


In [15]:
print(score.shape)

torch.Size([3])


In [18]:
c = torch.tensor([1,2,3])
d = torch.tensor([[1],[2],[3]])

print(c.shape)
print(c)
print(d.shape)
print(d)

torch.Size([3])
tensor([1, 2, 3])
torch.Size([3, 1])
tensor([[1],
        [2],
        [3]])


In [20]:
e=d.T
print(e.shape)
print(e)

torch.Size([1, 3])
tensor([[1, 2, 3]])


In [23]:
f = torch.tensor([1,2,3])
print(f.shape)

torch.Size([3])


In [28]:
c = (1,2,3)
d = ([1,2,3])
e = ([[1],[2],[3]])
f = ([1],[2],[3])
g = ([[1,2,3]])
print(c)
print(d)
print(f)
print(e)
print(g)


(1, 2, 3)
[1, 2, 3]
([1], [2], [3])
[[1], [2], [3]]
[[1, 2, 3]]


In [36]:
a = torch.tensor([1,2,3])  #元组
b = torch.tensor([1,2,3]) #列表
c = torch.tensor([1,2,3])  #一维张量
d = torch.tensor([[1,2,3]]) #一行三列，外层只有一个元素，这里的元素里装了3个数
e = torch.tensor([[1],[2],[3]])  #这是一个三行1列的 二维张量
f = torch.tensor([[1,2],[2,3],[3,4]]) #这是一个三行两列的 二维张量
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)


tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])
tensor([[1, 2],
        [2, 3],
        [3, 4]])


In [43]:
#自己测试广播
h = torch.tensor([[1,2,3],[1,2,3],[1,2,3]])
g = torch.tensor([[2,3]])
g_ok = torch.tensor([[2,3,4]])
print(h+g_ok)

tensor([[3, 5, 7],
        [3, 5, 7],
        [3, 5, 7]])


In [45]:
h = torch.tensor([[1,2,3],[1,2,3],[1,2,3]])
g = torch.tensor([[2]])
print(h*g)

tensor([[2, 4, 6],
        [2, 4, 6],
        [2, 4, 6]])
