In [11]:
%matplotlib inline  #导入一个原始的画图的库
import random   # 导入一个python的随机数的库
import torch   # 导入一个torch,所有的矩阵运算， 广播机制运算， 张量的表示，都需要用到torch 还有normal正态分布，matxul 矩阵乘法 matrix multipule 
from d2l import torch as d2l #从d2l中导入一个torch的库，命名为 d2l
gen = deta_iter(batch_size, feature, labels)   # 先创建生成器,不取值

In [29]:
def synthetic_data(w,b,num_example):  #定义一个函数叫synthetic_data 生成随机数 导入参数是w,b,num_example)
    "生成 y= Xw + b +噪声"   #这是线性回归的方程定义
    X = torch.normal(0,1,(num_example,len(w)))  #均值 标准差 在这里我们先生成一个正态分布以 0 mean ,1 (num_example数量的 长度是w的个数）的矩阵，len就是将w竖着排吗获取有几个特征） num_example是我们要的样本个数，以0为中心，1是控制数据散的有多开 生成一个w x num_example数量的矩阵 我们得到了这1000个人的腿部力量和背包重量
    y = torch.matmul(X,w)+b  #这里我们用X我们生成的矩阵方程去 和W 向量相乘 这里我们用真实的w就是特征 去乘上我们生成的正态分布的随机数，并且加上了偏置，我们就得到了我们要的答案 就是这1000个人的下山时间
    y += torch.normal(0,0.01,y.shape) #这里我们需要加一些噪音比如有些人的状态不是很好感冒了之类的，模拟真实的情况， 我们用正态分布去生成一个非常小的震荡 只有0.01 还是以0为中心  这两个专业名词我总是记不住
    return X,y.reshape((-1,1)) #返回X矩阵和 y向量 -1是我们不知道会输入多少个num_example，所以我们要全部， 1就是1列就是向量的形状竖

true_w = torch.tensor([2,-3.4])  #这里我们必须要使用tensor  （matmul矩阵乘法是张量库自己实现的一套底层算法， 函数外面一定要用圆括号
true_b = (4.2)
num_example = (1000)
features ,labels = synthetic_data(true_w,true_b,num_example) #这里我们输入参数，并且调用函数将x和y赋值给feature 和labels ,feature 就是我们的特征矩阵腿部力量和背包重量，labels就是我们向量答案算出来的下山时间，我们要根据腿部力量和背包重量来推测这1000个人下山可能会用多长时间来和真实的labels 做比较


In [100]:
def data_iter(bactch_size,features,labels): #这里我们定义了一个数据迭代 iteration  目的是把数据分批给模型进行训练一次给过去太大
    num_examples = len(features)  #我们先获取下这个特征的长度
    #print ("样本的长度是",num_examples)
    indices = list(range(num_examples)) #我们先建立一个列表，创建一个和num_example长度一样的下标
    random.shuffle(indices) #然后我们打乱这些下标
    #print("我们打乱的当前的索引下标是",indices[:10]) #我们先看一下这些下标是否被打乱 indices[10]这里的10表示第10个元素 想要打印10个元素indices[:10]
    for i in range(0,num_examples,batch_size):  #我们让i开始创建一组数，从0开始， 总长度是num_example ,步长是10  就是我一次只生成10个数 (这里是10 20 30 从里面切出来的数值 只是数据打乱了取数值的位置还是按顺序来的
        batch_indices = torch.tensor(indices[i:min(i+batch_size,num_examples)]) #这里的含义是我要一个张量的形式， 从我刚才打乱的indices里面取，从0开始取10个，总长度是num_example ,如果取的余数不满10个就当是min 不要报警就当最后一个批次的数量
        #print("当前的批次号 :", batch_indices) #我们可以答应出来当前的10个乱的批次号看看是什么样的
        #print("i :", i)
        yield features [batch_indices],labels[batch_indices] #我们这里给出了下标为batch_indices的feature的10个张量的数值，和下标为batcg_indices的打乱的从labels里取出来的10个张量的数值 用作返回 这里虽然没有用到return 但是这里的yeild feature 和labels就是当前一个循环的返回值
        #但 features 是一个 Tensor,不是普通 list——Tensor 的方括号 [] 支持一种特殊语法:如果你传进去的不是单个数字,而是一整个"由多个下标组成的张量",它会理解成:"把这些下标对应的所有那些行,一次性、批量地取出来,打包成一个新的张量返回给我"。
        
batch_size = 10 #这里我们先定义batch_size是10
for x,y in deta_iter(batch_size,feature,labels): #用for循环来接住当前批次的10个 特征值矩阵和答案向量 奇怪的是这里不用告诉x 和y 里面是什么我只管给它传，它什么都吃
    print (x,'\n',y)
    break
    

样本的长度是 1000
我们打乱的当前的索引下标是 [655, 722, 75, 217, 818, 419, 498, 782, 835, 14]
当前的批次号 : tensor([655, 722,  75, 217, 818, 419, 498, 782, 835,  14])
i : 0
tensor([[ 0.0310, -1.4931],
        [-0.0564, -0.4356],
        [-1.1876, -1.6045],
        [-0.3119,  0.4083],
        [-0.5911,  0.6438],
        [-0.8003,  0.3301],
        [ 0.2637, -2.3125],
        [-1.1712,  0.7666],
        [ 1.1158, -0.9538],
        [-2.0642, -0.5591]]) 
 tensor([[ 6.0625],
        [ 9.5494],
        [-1.7035],
        [ 5.1655],
        [ 6.5807],
        [ 5.5906],
        [ 4.6174],
        [14.1518],
        [10.4531],
        [ 4.6980]])


In [101]:

x, y = next(gen)
print(x, '\n', y)

当前的批次号 : tensor([901, 221, 213, 677, 444, 649, 883, 165, 286, 634])
i : 70
tensor([[ 0.0604,  1.1415],
        [ 0.1507,  0.1399],
        [-0.1126,  1.8715],
        [ 0.9214,  2.2759],
        [ 0.7306,  1.3443],
        [-0.4232,  0.1553],
        [-1.0010,  0.5620],
        [ 2.9667,  0.1717],
        [-0.2175, -0.2932],
        [ 1.0449,  1.9064]]) 
 tensor([[7.6294],
        [2.2754],
        [4.4910],
        [8.5912],
        [6.7390],
        [4.3064],
        [2.9946],
        [9.2713],
        [6.8083],
        [3.4483]])


In [102]:
w=torch.normal(0,0.01,size=(2,1),requires_grad =True)
b=torch.zeros(1,requires_grad =True)

In [103]:
def linreg(X,w,b):   #这里我们定义了线性回归的模型，有3个参数，特征矩阵X ,w特征权重，外部影响偏置+b 
    """线性回归模型"""
    return torch.matmul(X,w)+b #这里返回的是每一个人花费的时间， 矩阵X 和特征向量相乘 加上偏置 得到花费的时间

In [104]:
def squared_loss(y_hat,y):
    """均方损失"""
    return ((y_hat-y.reshape(y_hat.shape))**2/2) #这里我们将刚才线性回归模型得到的答案 y_hat - 我们本来就知道的答案，hat 得到了每个人的损失，然后将每个人的损失的平方 这里/2是为了后面求梯度反向传播使用的
    #y_hat - y 这里很直白模型猜的答案-真实的答案 得到了猜错的误差， y.reshape(y_hat.shape) 这里的意思是强制把y的形状调成y_hat一样的形状 这样方便相减，如果形状不同不能相减

In [105]:
def sgd(params,lr,batch_size):  #sgd 是   params: 损失，是预测错误的时间差  lr：是学习率  batch_size是步长 
    """小批量随机梯度下降"""      #
    with torch.no_grad():  #现在开始torch不记录梯度
        for param in params: #for 
            param -= lr * param.grad/batch_size   #我这里要更新我的梯度，我要用我的学习率* 我的差的导数/有多少个人 或者可以说我知道高度的差值可以反向求哪边下降的最快，所以我这里是求偏导吗为什么要/10 都没有把它们都加起来这个公式里， 可能前面会出现一个把10个人的损失都加起来，然后求偏导，求完了偏导之后我们知道了哪个方向最快还是说我一个一个人先求偏导， 
            param.grad.zero_()                    #我只知道，我在当前的坐标求偏导我知道哪个方向是爬山最快是吗， 但是我现在知道了我已经爬了的高度反向求我应该往哪个方向走大致是这个意思吗， 然后我求出来的方向是正的反向所以我要把它换成反的方向，然后更新梯度又是是吗意思，，我先理解一下，我之前知道X1 和 x2的位置， 我通过求导数的方式可以知道哪个方向爬山最快，我要知道我爬了多高吗， 我不知道我本来也不熟悉这里的计算，反正我觉得就是知道了高度然后反着求出来哪个方向是向下至于梯度，梯度是什么梯度不就是两个方向的表示值就叫梯度吗
                                                 # 我现在知道高度差反向求梯度是这个意思吗 我已经忘记了梯度是什么了 最后一个param.grad.zero_()  是把梯度清零的意思吗
            

In [107]:
lr =0.03
num_epochs =3 
net = linreg 
loss = squared_loss

for epoch in range (num_epochs):
    for X,y in data_iter(batch_size,features,labels):
        l=loss(net(X,w,b),y)
        l.sum().backward()
        sgd([w,b],lr,batch_size)
        with torch.no_grad():
            train_l = loss (net(features,w,b),labels)
    print(f'epoch{epoch + 1}, loss{float(train_l.mean()):f}')

epoch1, loss0.000051
epoch2, loss0.000051
epoch3, loss0.000050


In [109]:
print(f'w的误差:{true_w - w.reshape(true_w.shape)}')
print(f'b的误差:{true_b - b}')

w的误差:tensor([-2.9325e-05,  1.4138e-04], grad_fn=<SubBackward0>)
b的误差:tensor([-9.2506e-05], grad_fn=<RsubBackward1>)


In [113]:
import os 
print (os.getcwd())

/mnt/c/Users/Jorin
