In [1]:
import torch
print(torch.__version__)

2.12.1


In [2]:
#创建一个张量的排列
import torch 
x = torch.arange(12)
print(x)
print(x.shape)
print(type(x))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
<class 'torch.Tensor'>


In [5]:
#重新定义张量的形状
y = x.reshape(3,4)
print(y)
print(y.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [9]:
#用python列表来赋值张量中的每个元素
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])


tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [21]:
#张量结合
x= torch.arange(12,dtype=torch.float32).reshape((3,4))
y= torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [31]:
x[-1],x[1:3]#1:3就是第一行到第三列

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [32]:

x[1,3]=9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  9.],
        [ 8.,  9., 10., 11.]])

In [34]:
#运行一些操作可能会导致新结果分配
before= id(y)
y= y+ x
id(y) ==before

False

In [43]:
#执行原地操作
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:]=x+y
print('id(z):', id(z))

id(z): 5539590336
id(z): 5539590336


In [45]:
before=id(x)
x+=y
id(x)==before

True

In [22]:
#逻辑运算符
x==y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [23]:
#求和
x.sum()

tensor(66.)

In [48]:
#转换为Numpy张量
A= x.numpy()
B =torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [49]:
#将大小为1的张量转换为python标量
a = torch.tensor([3.5])
a,a.item(),float(a), int(a)



(tensor([3.5000]), 3.5, 3.5, 3)

In [24]:
#广播机制
a= torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
print(a)
print(b)
print(a+b)
a,b


tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [11]:
import torch 
x = torch.arange(12).reshape(3,4)
print(x)
s = x.sum()
print(s)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor(66)


In [27]:
print(x[0]) #取第0行
print(x[1]) #取第一行
print(x[2]) #取第二行
print(x[-1]) #取最后一行，这个的意思是从后往前数的di yi
x[-1]
x[1,3]

tensor([0., 1., 2., 3.])
tensor([4., 5., 6., 7.])
tensor([ 8.,  9., 10., 11.])
tensor([ 8.,  9., 10., 11.])


tensor(7.)

In [30]:
x[-1], x[1,3]

(tensor([ 8.,  9., 10., 11.]), tensor(7.))

In [24]:
#索引和张量
print(x[1,2])   #打印第一行 第二个数字
print(x[2,3])   #打印第二行 第一个数字，记住张量有第0行 python所有的索引都是从0开始  
print(x[0,2])
print(x[:,1])   #取所有行的第一列
print(x[1:3,2:4])#取1-2行，第2-3列
print(x[2,1])
print(x[:,2])
print(x[0:2,1:3])  #这里有个左闭右开的原则 ，左边包含右边不包含就是我写2 就是取1 ，我写4就是取3
print(x[1:2,5:6])

tensor(6)
tensor(11)
tensor(2)
tensor([1, 5, 9])
tensor([[ 6,  7],
        [10, 11]])
tensor(9)
tensor([ 2,  6, 10])
tensor([[1, 2],
        [5, 6]])
tensor([], size=(1, 0), dtype=torch.int64)


In [3]:
import os 
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..','data','welding.csv')

with open(data_file, 'w') as f:
    f.write('电流,电压,压力,焊接质量\n')
    f.write('150,220,3.5,良好\n')
    f.write('160,NA,3.8,良好\n')
    f.write('145,215,NA,不良\n')
    f.write('145,215,NA,不良\n')


In [4]:
import os  
#用os库创建csv文件，存储焊接参数
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'welding.csv')

with open(data_file, 'w') as f:
    f.write('电流,电压,压力,焊接质量\n')
    f.write('150,220,3.5,良好\n')
    f.write('160,NA,3.8,良好\n')
    f.write('145,215,NA,不良\n')
    f.write('170,230,4.0,良好\n')

In [5]:
import pandas as pd 
#用pandas 读取csv发现缺失值NaN
data = pd.read_csv(data_file)
print(data)

    电流     电压   压力 焊接质量
0  150  220.0  3.5   良好
1  160    NaN  3.8   良好
2  145  215.0  NaN   不良
3  170  230.0  4.0   良好


In [7]:
#用每列的平方值填充缺失值
inputs = data.iloc[:,0:3]  #取前3列（电流，电压，压力）
inputs = inputs.fillna(inputs.mean())
print(inputs)

    电流          电压        压力
0  150  220.000000  3.500000
1  160  221.666667  3.800000
2  145  215.000000  3.766667
3  170  230.000000  4.000000


In [8]:
import torch  用平均值NaN再转成张量给模型用
x=torch.tensor(inputs.values)
print(x)

tensor([[150.0000, 220.0000,   3.5000],
        [160.0000, 221.6667,   3.8000],
        [145.0000, 215.0000,   3.7667],
        [170.0000, 230.0000,   4.0000]], dtype=torch.float64)


In [3]:
import torch
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a)
print(b)


tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


In [7]:
print (a + b)

tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [10]:
#模拟3条焊接记录，每行是【电流，电压，压力】
data = torch.tensor([[150.0,220.0,3.5],
                    [160.0,225.0,3.8],
                    [145.0,215.0,3.6]])

#权重：电流权重0.6 电压权重0.3 压力权重0.1 
weight = torch.tensor([0.6,0.3,0.1])

print(data.shape)
print(weight.shape)

torch.Size([3, 3])
torch.Size([3])


In [11]:
result = data * weight 
print(result)

tensor([[90.0000, 66.0000,  0.3500],
        [96.0000, 67.5000,  0.3800],
        [87.0000, 64.5000,  0.3600]])


In [13]:
score = (data * weight).sum(dim = 1)
print(score)

tensor([156.3500, 163.8800, 151.8600])


In [15]:
print(score.shape)

torch.Size([3])


In [18]:
c = torch.tensor([1,2,3])
d = torch.tensor([[1],[2],[3]])

print(c.shape)
print(c)
print(d.shape)
print(d)

torch.Size([3])
tensor([1, 2, 3])
torch.Size([3, 1])
tensor([[1],
        [2],
        [3]])


In [20]:
e=d.T
print(e.shape)
print(e)

torch.Size([1, 3])
tensor([[1, 2, 3]])


In [23]:
f = torch.tensor([1,2,3])
print(f.shape)

torch.Size([3])


In [28]:
c = (1,2,3)
d = ([1,2,3])
e = ([[1],[2],[3]])
f = ([1],[2],[3])
g = ([[1,2,3]])
print(c)
print(d)
print(f)
print(e)
print(g)


(1, 2, 3)
[1, 2, 3]
([1], [2], [3])
[[1], [2], [3]]
[[1, 2, 3]]


In [36]:
a = torch.tensor([1,2,3])  #元组
b = torch.tensor([1,2,3]) #列表
c = torch.tensor([1,2,3])  #一维张量
d = torch.tensor([[1,2,3]]) #一行三列，外层只有一个元素，这里的元素里装了3个数
e = torch.tensor([[1],[2],[3]])  #这是一个三行1列的 二维张量
f = torch.tensor([[1,2],[2,3],[3,4]]) #这是一个三行两列的 二维张量
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)


tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])
tensor([[1, 2],
        [2, 3],
        [3, 4]])


In [36]:
#自己测试广播
import torch
h = torch.tensor([[1,2,3],[1,2,3],[1,2,3]])
g = torch.tensor([[2,3]])

g_ok = torch.tensor([[2,3,4]])
print(h+g_ok)
#print(h+g)

i= torch.tensor([[2,3,4],[2,3,4]])
j= torch.tensor([[3],[4]])
print(i+j)
print(i.shape)
print(j.shape)


tensor([[3, 5, 7],
        [3, 5, 7],
        [3, 5, 7]])
tensor([[5, 6, 7],
        [6, 7, 8]])
torch.Size([2, 3])
torch.Size([2, 1])


In [45]:
h = torch.tensor([[1,2,3],[1,2,3],[1,2,3]])
g = torch.tensor([[2]])
print(h*g)

tensor([[2, 4, 6],
        [2, 4, 6],
        [2, 4, 6]])


In [7]:
import torch
data =torch.tensor([[150.0,220.0,3.5],
                   [160.0,255.0,3.8],
                   [145.0,215.0,3.6]])
result_a =data.sum(dim = 1)
print (result_a.shape)
print(result_a)

torch.Size([3])
tensor([373.5000, 418.8000, 363.6000])


In [17]:
#上面的二维张量 压缩掉一个维度，变成一维张量，现在我们用一个三维的张量进行压缩成两维观察结果
#1维 ：[1,2,3,4] 只有一层方括号 shape(4,) 就是一排数没有行列的概念
#2维 ： shape(2,3) 
#    [[1,2,3],
#      4,5,6]]就是两行三列
#3维 ：shape[2,2,3]
#    [[[1,2,3],
#       4,5,6]]
#    [[[7,8,9],
#     10,11,12]]]
#    3维就是两个表格先叠加
#4维 ：就是有两个相同的叠加的3维Excel表
#5维：就是 ？
import torch
t3 = torch.tensor([[[1,2,3],
              [4,5,6]],

             [[7,8,9],
              [10,11,12]]])
print(t3.shape)
t0 = (t3.sum(dim =0))
print(t0)
print(t0.shape)
t1 = (t3.sum(dim =1))
print(t1)
print(t1.shape)
t2 = (t3.sum(dim =2))
print(t2)
print(t2.shape)

      

torch.Size([2, 2, 3])
tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])
tensor([[ 5,  7,  9],
        [17, 19, 21]])
torch.Size([2, 3])
tensor([[ 6, 15],
        [24, 33]])
torch.Size([2, 2])


In [5]:
result_b = data.sum(dim=1, keepdim = True)
print(result_b.shape)
print(result_b)

torch.Size([3, 1])
tensor([[373.5000],
        [418.8000],
        [363.6000]])


In [8]:
#写法A： 用没有keepdim的结果
try:
    ratio_a = data/result_a
    print("写法A成功")
    print(ratio_a)
except Exception as e :
    print("写法A失败: ", e)
#写法B： 用keepdim的结果
try:
    ratio_b = data /result_b
    print("写法B成功")
    print(ratio_b)
except Exception as e:
    print("写法B失败： ",e)
    
    

写法A成功
tensor([[0.4016, 0.5253, 0.0096],
        [0.4284, 0.6089, 0.0105],
        [0.3882, 0.5134, 0.0099]])
写法B成功
tensor([[0.4016, 0.5890, 0.0094],
        [0.3820, 0.6089, 0.0091],
        [0.3988, 0.5913, 0.0099]])


In [4]:
import torch

a=torch.tensor([150,220,3.5])
b=torch.tensor([0.01,0.005,2.0])
#torch.dot(a,b) = 150*0.01 + 220*0.005 +3.5*2.0 =9.6
c =torch.dot(a,b)
print(c)

tensor(9.6000)


In [7]:
import d2l
import torchvision
print("都装好了")


都装好了


In [52]:
#数据预处理。创建一个人工数据集，并存储在csv
import os

os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n') #列名
    f.write('NA,Pave,127500\n') #每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')


In [54]:
#从创建的csv文件中加载原始数据集
#pip install pandas 
import pandas as pd  #把pandas整个库导入进来，as这个关键字的作用是给刚才导入的东西重新取一个名字
print (pd.__version__)
data = pd.read_csv(data_file)
#print(data)
data  #如果不print 会更紧凑


2.0.3


,NumRooms,Alley,Price
0,NaN,Pave,127500
1,2.0,NaN,106000
2,4.0,NaN,178100
3,NaN,NaN,140000


In [64]:
#未了处理缺失的数据，典型的方法包括插值，删除，这里我们考虑插值
inputs,outputs =data.iloc[:,0:2],data.iloc[:,2]
# 单独一个：表示所有行都要，0:2切出来就是切片，slice写法，从索引0开始一直索引到2 但不包含2，0列和1列但不包含2列
#0:2 是一个范围，0-1范围内的列都要，
#单独一个2就是 我只要2这一个列
#inputs = inputs.fillna(inputs.mean())
inputs = inputs.fillna(inputs.mean(numeric_only = True))
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [61]:
# 对于inputs中的类别值或者离散值，我们将NaN视作一个类别
#现在可以直接转成张量,喂给模型了。
inputs = pd.get_dummies(inputs,dummy_na = True)
print(inputs)


   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


In [63]:
#现在inputs 和 outputs 中所有的条目都是数值类型，它们可以转换成张量的格式
#.astype(float)
import torch
x,y = torch.tensor(inputs.values.astype(float)),torch.tensor(outputs.values)
x,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [67]:
#转换为Numpy张量
A= x.numpy()  #转换成numpy的张量
B= torch.tensor(A) #转换成tensor的张量
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [69]:
#将大小为1的张量转换为Python标量
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [ ]:
#我们来模拟广播机制

In [72]:
A = torch.arange(20*2).reshape(2,5,4)
A.shape,A.sum()
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [76]:
A= torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [83]:
A =torch.arange(20*2).reshape(2,5,4)
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [97]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1,A_sum_axis1.sum

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 <function Tensor.sum>)

In [86]:
A.sum(axis=[0,1])

tensor([180, 190, 200, 210])

In [92]:
#
#A =torch.arange(20*2).reshape(2,5,4)
sum_A =A.sum(axis=1,keepdims=True)
sum_A

tensor([[[ 40,  45,  50,  55]],

        [[140, 145, 150, 155]]])

In [93]:
sum_A =A.sum(axis=1)
sum_A

tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]])

In [94]:
a/sum_A

tensor([[0.0875, 0.0778, 0.0700, 0.0636],
        [0.0250, 0.0241, 0.0233, 0.0226]])

In [96]:
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [95]:
A.cumsum(axis=0)
#从第二个块开始累加上了第一个块的值

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]])

In [99]:
A =torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [101]:
B=torch.arange(12).reshape(4,3)
B

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [102]:
torch.mm(A,B)

tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262],
        [258, 312, 366],
        [330, 400, 470]])

In [106]:
B=torch.ones(4,3)
B
#创建一个指定形状的的张量里面全部填成1 


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [107]:
A =torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [109]:
B = torch.ones(4,3)
B

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [111]:
torch.mm(A.float(),B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [116]:
#L1范数 
u= torch.tensor([3.0,-4.0])
torch.abs(u).sum()

tensor(7.)

In [114]:
#矩阵的frobenius norm 是矩阵元素的平方和的平方根
torch.norm(torch.ones((4,9)))

tensor(6.)

In [123]:
A= torch.arange(20).reshape(5,4)
A


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [125]:
A.sum(axis=0)

tensor([40, 45, 50, 55])

In [126]:
A.sum(axis=1)

tensor([ 6, 22, 38, 54, 70])